console.log("testing");
console.log("Hello, TypeScript!^^");
console.log("dssaaad");
console.log("Hello, TypeScript!^^");
console.log("test222");
console.log("test");
console.log("ddd");
console.log("Hello, TypeScr");
console.log("ddddd");
console.log("Hello, TypeScript!^^");
console.log("Hello, TypeScript!^^");
